/**
 * icp-cli Project Manifest Generation
 *
 * The external `icp` CLI (icp-cli) requires an `icp.yaml` project manifest.
 * Its schema (canisters/environments as sequences) is different from
 * AgentVault's internal environment config, so generated agent projects
 * need their own manifest for `icp deploy` to work.
 *
 * The generated manifest uses a plain script build step that copies the
 * packaged WASM into place. This avoids the remote recipe registry
 * (e.g. @dfinity/prebuilt), whose templates are not compatible with all
 * icp-cli binary versions.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Header marker identifying manifests generated by AgentVault.
 * Manifests without this marker are never overwritten.
 */
export const GENERATED_MARKER = '# Generated by agentvault';

/**
 * Resolve the project root for a packaged WASM file.
 * Packaged agents place WASM in `<project>/dist/<name>.wasm`, so the
 * parent of a `dist` directory is treated as the project root.
 */
export function resolveProjectRootForWasm(wasmPath: string): string {
  const absWasm = path.resolve(wasmPath);
  const dir = path.dirname(absWasm);
  return path.basename(dir) === 'dist' ? path.dirname(dir) : dir;
}

/**
 * Path of the icp.yaml manifest for a project root.
 */
export function icpManifestPath(projectRoot: string): string {
  return path.join(projectRoot, 'icp.yaml');
}

export interface EnsureManifestResult {
  /** Absolute path to the manifest */
  path: string;
  /** What happened: created new, refreshed a generated one, or kept a user-managed one */
  action: 'created' | 'updated' | 'kept';
}

/**
 * Ensure an icp-cli-compatible manifest exists for the project.
 *
 * - No icp.yaml: writes one referencing the packaged WASM.
 * - Existing icp.yaml with the AgentVault marker: rewritten (WASM path or
 *   agent name may have changed since the last package).
 * - Existing icp.yaml without the marker: left untouched.
 *
 * @param projectRoot - Agent project root directory
 * @param canisterName - Canister name (usually the agent name)
 * @param wasmPath - Path to the packaged WASM file
 */
export function ensureIcpManifest(
  projectRoot: string,
  canisterName: string,
  wasmPath: string
): EnsureManifestResult {
  const manifestPath = icpManifestPath(projectRoot);
  const exists = fs.existsSync(manifestPath);

  if (exists) {
    const current = fs.readFileSync(manifestPath, 'utf-8');
    if (!current.startsWith(GENERATED_MARKER)) {
      return { path: manifestPath, action: 'kept' };
    }
  }

  const relWasm = path
    .relative(projectRoot, path.resolve(wasmPath))
    .split(path.sep)
    .join('/');

  const content = [
    `${GENERATED_MARKER} — regenerated on each \`agentvault package\`; remove this header line to manage it yourself.`,
    'canisters:',
    `  - name: ${canisterName}`,
    '    build:',
    '      steps:',
    '        - type: script',
    '          commands:',
    `            - cp "${relWasm}" "$ICP_WASM_OUTPUT_PATH"`,
    '',
  ].join('\n');

  fs.writeFileSync(manifestPath, content, 'utf-8');
  return { path: manifestPath, action: exists ? 'updated' : 'created' };
}
